version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dashboard:/etc/nginx/html/dashboard
      - ./product:/etc/nginx/html/product
      - ./cart:/etc/nginx/html/cart
    ports:
      - "80:80"
    command: >
      /bin/sh -c "chown -R nginx:nginx /etc/nginx/html && chmod -R 755 /etc/nginx/html && nginx -g 'daemon off;'"
